### ISSUE TITLE
audio track error

### ISSUE THREAD

**Issue by guestuser22** [Stremio/stremio-core-web#107]
i am using stremio web + real debrid + torrentio.
i am not using stremio service for windows because edge plays hdr and dolby audio content fine. 

v0.47.1 used to work perfectly but for two days (ig v0.47.2 is the culprit here), the audio for some reason is russian (when i am watching constellation) or russian + english together (when i am watching ted). 

in stremio web settings, default audio track is set to english.

**Comment by TRtomasz** [comment]
default audio track will not work if you dont have service/server running.

**Comment by guestuser22** [comment]
why this regressive change? it used to work nicely earlier. 

edit: 
i installed the web service and the streaming status is online. 
but still the videos (hdr/dv) won't play and the videos that are playing have the same audio issue stated above. 
default language selector is not working.
