### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by eramax** [Stremio/stremio-core-web#12]
Hi
I tried to build the package but having this issue 

`   
Compiling wasm-bindgen v0.2.60
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/eramax/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.60/src/lib.rs:10:34
   |
10 | #![cfg_attr(feature = "nightly", feature(unsize))]
   |                                  ^^^^^^^^^^^^^^^

   Compiling proc-macro-crate v0.1.4
error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `wasm-bindgen`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @stremio/stremio-core-web@0.12.0 build: `./build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @stremio/stremio-core-web@0.12.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eramax/.npm/_logs/2020-06-21T09_14_14_170Z-debug.log

`

Regards

**Comment by nklhrstv** [comment]
Hi @eramax 
You need to set the default toolchain to nightly by `rustup default nightly`
then you probably need to update by `rustup update`
and finally you can try run `npm run build`

**Comment by nklhrstv** [comment]
0.17.0 now uses rust 1.45.0 on the CI
