### ISSUE TITLE
Build success but I can't run

### ISSUE THREAD

**Issue by mikdanjey** [Stremio/stremio-core-web#38]
I have done this complete setup, How to run this PORT 11470.

Please help me.

![image](https://user-images.githubusercontent.com/17296759/210154708-be1ef014-2ff6-4bad-a6b2-8295f45fc0a5.png)

**Comment by elpiel** [comment]
Please refer to https://github.com/Stremio/stremio-web which is the actual web interface.
This repository is only for the bridge between the Rust core and the web interface and does not have any application that you can run.

**Comment by manikandan-anjamerica** [comment]
@elpiel - I can run this Web UI of https://github.com/Stremio/stremio-web 

in this Web UI needs Server, Right ? - https://github.com/Stremio/stremio-core-web.git

**How to run this Stremio Server for web ?**

**Comment by elpiel** [comment]
the easiest way to run the server is by using either [stremio-service](https://github.com/Stremio/stremio-service/) or running the docker container: https://hub.docker.com/r/stremio/server (you will probably need to tweak some parameters like passing `NO_CORS=1` if you run a local instance of `stremio-web` iirc)

**Comment by mikdanjey** [comment]
I need stremio-service version 5

The stremio-web version is 5, due to this not connecting

**Comment by elpiel** [comment]
@mikdanjey Stremio service bundles the server and auto-starting of the server as an Tray app.
It's version is not related to stremio-web, as stremio-web only looks for a running server.
For running local stremio-web with stremio-service, make sure to start the service with env. variable `NO_CORS=1` and try again. The value is passed to stremio-server.

**Comment by elpiel** [comment]
Closing this issue as off-topic and since there hasn't been any development in the issue.
